# Generated by Django 5.0.7 on 2024-12-14 08:20

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aml_code',
            field=models.CharField(default=bank_app.models.generate_aml, max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imf_code',
            field=models.CharField(default=bank_app.models.generate_imf, max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tac_code',
            field=models.CharField(default=bank_app.models.generate_tac, max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linking_code',
            field=models.CharField(default=bank_app.models.generate_code, max_length=11),
        ),
    ]
